spring.application.name=color-game
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Stage
spring.datasource.username=postgres
spring.datasource.password=dejihed
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
jwt.secret=dejihed

# Adjust based on your needs
